added actionbar and overflow menu with settings
unstablebrainiac/Tum-Tum-Tracker pull request #5
Opened 2017-05-29 19:02 UTC by shubhangb97

2017-06-01 11:11 UTC, unstablebrainiac requested changes
Just 3 small changes, and then we'll merge

2017-06-01 11:11 UTC, unstablebrainiac commented on app/src/main/res/menu/settings_menu.xml
> +<?xml version="1.0" encoding="utf-8"?>
Rename this file to `main.xml`

2017-06-01 11:11 UTC, unstablebrainiac commented on app/src/main/res/values/strings.xml
> +    <string name="settings">settings</string>
Settings with a capital 'S'

2017-06-01 11:11 UTC, unstablebrainiac commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +        getSupportActionBar().setTitle("Tum Tum Tracker");
Fetch app name from `strings.xml` instead of hard coding

2017-06-01 14:30 UTC, shubhangb97 commented
Done the changes

2017-06-03 14:32 UTC, shubhangb97 commented
added button to zoom to current location

2017-06-03 15:21 UTC, unstablebrainiac requested changes

2017-06-03 15:21 UTC, unstablebrainiac commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
This does not work as expected on my phone. I get a permission prompt and on clicking _Allow_, there are 2 consecutive toasts _Need Permission_ and _Restart after giving permission_ in that order

2017-06-04 12:52 UTC, shubhangb97 commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
After giving the permission if we restart the app it works pefectly. I will try to correct it,looks like an issue in the API

2017-06-04 15:04 UTC, shubhangb97 commented
resolved the permission restart issue

2017-06-07 10:49 UTC, unstablebrainiac commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +import static android.support.v4.content.PermissionChecker.PERMISSION_GRANTED;
What is this for?

2017-06-07 10:51 UTC, unstablebrainiac approved these changes

2017-06-07 10:55 UTC, shubhangb97 commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +import static android.support.v4.content.PermissionChecker.PERMISSION_GRANTED;
Thats a static int constant  to check if permission was granted or not used in onPermissionRequestCallBack() method

2017-06-07 10:59 UTC, unstablebrainiac commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +import static android.support.v4.content.PermissionChecker.PERMISSION_GRANTED;
You can use it without the import. Try doing that

2017-06-07 11:18 UTC, unstablebrainiac commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +        if(grantResults[0]==getPackageManager().PERMISSION_GRANTED)
`static` variable hai, `PackageManager.PERMISSION_GRANTED` will do

2017-06-07 11:35 UTC, shubhangb97 commented on app/src/main/java/in/ac/iitb/gymkhana/tumtumtracker/MapsActivity.java
> +        if(grantResults[0]==getPackageManager().PERMISSION_GRANTED)
ab ho gaya Sorry androidStudio had auto imported those constants previously

2017-06-07 15:21 UTC, merged